// auto-generated by deployPerps.ts and extended for multi-market
// Switched to BSC networks (bscTestnet/bsc)
export const deployed = {
  bscTestnet: {
    btcd: { oracle: '', perps: '' },
    random: { oracle: '', perps: '' },
    localaway: { oracle: '', perps: '' }
  },
  bsc: {
    btcd: { oracle: '', perps: '' },
    random: { oracle: '', perps: '' },
    localaway: { oracle: '', perps: '' }
  }
} as const;
